name: VinLogistics
options:
  bundleIdPrefix: com.vinlogistics
  deploymentTarget:
    iOS: "17.0"
  developmentLanguage: de
  usesTabs: false
  indentWidth: 4
  tabWidth: 4
  xcodeVersion: "15.0"

targets:
  VinLogistics:
    type: application
    platform: iOS
    sources:
      - path: VinLogistics
    resources:
      - path: VinLogistics/Resources
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.vinlogistics.app
      INFOPLIST_FILE: VinLogistics/Info.plist
      SWIFT_VERSION: "5.9"
      IPHONEOS_DEPLOYMENT_TARGET: "17.0"
      TARGETED_DEVICE_FAMILY: "1" # iPhone only
    dependencies:
      - framework: Vision.framework
      - framework: SwiftUI.framework
      - framework: SwiftData.framework

schemes:
  VinLogistics:
    build:
      targets:
        VinLogistics: all
    run:
      config: Debug
    test:
      config: Debug

