name: VinLogistics
options:
  bundleIdPrefix: com.vinlogistics
  deploymentTarget:
    iOS: "17.0"
  developmentLanguage: de
  usesTabs: false
  indentWidth: 4
  tabWidth: 4
  xcodeVersion: "15.0"

targets:
  VinLogistics:
    type: application
    platform: iOS
    sources:
      - path: VinLogistics
    resources:
      - path: VinLogistics/Resources
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.vinlogistics.app
      INFOPLIST_FILE: VinLogistics/Info.plist
      SWIFT_VERSION: "5.9"
      IPHONEOS_DEPLOYMENT_TARGET: "17.0"
      TARGETED_DEVICE_FAMILY: "1" # iPhone only
      LINKED_FRAMEWORKS:
        - Vision.framework
        - SwiftUI.framework
        - SwiftData.framework

  VinLogisticsTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: VinLogisticsTests
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.vinlogistics.appTests
      SWIFT_VERSION: "5.9"
      IPHONEOS_DEPLOYMENT_TARGET: "17.0"
      GENERATE_INFOPLIST_FILE: true
    dependencies:
      - target: VinLogistics

  VinLogisticsUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: VinLogisticsUITests
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.vinlogistics.appUITests
      SWIFT_VERSION: "5.9"
      IPHONEOS_DEPLOYMENT_TARGET: "17.0"
      GENERATE_INFOPLIST_FILE: true
    dependencies:
      - target: VinLogistics

schemes:
  VinLogistics:
    build:
      targets:
        VinLogistics: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - name: VinLogisticsTests
        - name: VinLogisticsUITests

