name: OenoLog
options:
  bundleIdPrefix: com.oenolog
  deploymentTarget:
    iOS: "17.0"
  developmentLanguage: de
  usesTabs: false
  indentWidth: 4
  tabWidth: 4
  xcodeVersion: "15.0"

targets:
  OenoLog:
    type: application
    platform: iOS
    sources:
      - path: OenoLog
    resources:
      - path: OenoLog/Resources
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.oenolog.app
      INFOPLIST_FILE: OenoLog/Info.plist
      SWIFT_VERSION: "5.9"
      IPHONEOS_DEPLOYMENT_TARGET: "17.0"
      TARGETED_DEVICE_FAMILY: "1" # iPhone only
      LINKED_FRAMEWORKS:
        - Vision.framework
        - SwiftUI.framework
        - SwiftData.framework

  OenoLogTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: OenoLogTests
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.oenolog.appTests
      SWIFT_VERSION: "5.9"
      IPHONEOS_DEPLOYMENT_TARGET: "17.0"
      GENERATE_INFOPLIST_FILE: true
    dependencies:
      - target: OenoLog

  OenoLogUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: OenoLogUITests
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.oenolog.appUITests
      SWIFT_VERSION: "5.9"
      IPHONEOS_DEPLOYMENT_TARGET: "17.0"
      GENERATE_INFOPLIST_FILE: true
    dependencies:
      - target: OenoLog

schemes:
  OenoLog:
    build:
      targets:
        OenoLog: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - name: OenoLogTests
        - name: OenoLogUITests

